### ISSUE TITLE
Review/Campaign Report

### ISSUE THREAD

**Issue by learneradarsh** [MozUP/NIghtly-Campaign-Lucknow#3]
It's an awesome session.
Today.I've got new experience about Nightly and  Rust Programming.
Thanks to SwagLabs and Shivank.
(:

**Comment by thenooglerboy** [comment]
It is fantastic n awesome session with shivank sr.
Today ,I known a nightly mozilla firefox,,that is awesome
thanks...

**Comment by GeekyShiva** [comment]
thanks for the contribution
