### ISSUE TITLE
Review/Campaign Report

### ISSUE THREAD

**Issue by withshubh** [MozUP/NIghtly-Campaign-Lucknow#4]
It was my first workshop of Mozilla Uttar Pradesh which I attended. Shivank Shekhar Sir told all the attendees how we can setup Firefox Nightly on different platforms (mac,windows and linux) and using it by creating different profiles then he taught how we all can file bugs using Bugzilla and webcompat and these two are different from each other.
then next session was on Rust programming language in which we were taught what is Rust language and how it is different from other languages, then setting it up on linux,mac and windows. And then a program was created using rust language.
overall it was good interactive workshop and learned lot new things

**Comment by GeekyShiva** [comment]
thanks for the review ...hope to see more such contributions from your end :)
